### RTL over time

In [128]:
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import hvplot.pandas

In [129]:
# read in data
df = pd.read_csv('/Users/kermitbravo/Desktop/UT/Final Project/Predictive_Senescence/Resources/Data/Bird_Data/Bird_Data.csv')
df.head()

,Collection_Num,BirdID,Sex,AgeY,AgeClass,BirthFPID,U_PlateID,RTL,Technician,Terr,FPID,mum,dad,MAC,PAC,BrF,BrM
0,1,5511,0,0.246575,J,103,9_3,1.06,1,10.0,104,4863,1762,3.920548,7.443836,4863,1762
1,2,5559,1,3.597260,A,103,9_1,0.52,1,77.1,122,1716,1877,7.416438,6.235616,1716,4892
2,3,5559,1,4.715068,A,103,9_28,1.07,1,77.1,125,1716,1877,7.416438,6.235616,1716,4892
3,4,5559,1,0.657534,SA,103,9_2,0.99,1,111.0,104,1716,1877,7.416438,6.235616,1716,4892
4,5,5527,1,0.328767,OFL,103,9_3,1.02,1,131.0,104,4936,1710,3.452055,7.778082,1707,1710

 Need to add a column for time 
 
 steps: 
 1. sort BirdID
 2. for loop or something that says for each Bird ID look at AgeY and assign 1 to the smallest number a 2 to the next  and 3 to the next largest etc. 
 
 look at 
 3. look for patterns in the rate of change between time 1 and 2, 2 and 3 and so on- plot line graph
 4. could look at mean difference between times

In [132]:
df.sort_values(by=['BirdID','AgeY'], inplace=True)
df['Time'] = df.apply(lambda x: '', axis=1)
mask = df['BirdID'].duplicated(keep=False)

In [133]:
df.loc[mask, 'Time'] += df.groupby('BirdID').cumcount().add(1).astype(str)
df.head(30)

,Collection_Num,BirdID,Sex,AgeY,AgeClass,BirthFPID,U_PlateID,RTL,Technician,Terr,FPID,mum,dad,MAC,PAC,BrF,BrM,Time
2649,2650,51,1,10.386301,A,7,8_20,1.53,1,35.0,22,0,0,0.000000,0.000000,0,0,
2650,2651,64,0,10.501370,A,7,1_15,0.81,2,71.0,23,0,0,0.000000,0.000000,0,0,
2652,2653,163,0,9.350685,A,7,1_33,1.21,2,42.0,22,0,0,0.000000,0.000000,0,0,
2646,2647,176,1,6.704110,A,8,7_35,0.40,1,46.0,19,0,0,0.000000,0.000000,0,0,1
2659,2660,176,1,6.772603,A,8,7_32,0.93,1,46.0,19,0,0,0.000000,0.000000,0,0,2
2661,2662,176,1,13.873973,A,8,4_3,0.72,2,46.0,41,0,0,0.000000,0.000000,0,0,3
2647,2648,199,0,8.528767,A,6,2_21,0.32,2,30.0,19,0,0,0.000000,0.000000,0,0,1
2656,2657,199,0,15.676712,A,6,2_13,0.69,2,30.1,41,0,0,0.000000,0.000000,0,0,2
2658,2659,216,1,8.947945,A,8,8_8,1.18,1,37.0,22,0,0,0.000000,0.000000,0,0,
2655,2656,220,1,9.616438,A,8,1_40,0.69,2,20.0,23,0,0,0.000000,0.000000,0,0,
2657,2658,221,1,6.958904,A,8,2_1,1.99,2,32.0,19,0,0,0.000000,0.000000,0,0,1
2660,2661,221,1,9.090411,A,8,1_12,0.90,2,32.0,22,0,0,0.000000,0.000000,0,0,2
2651,2652,221,1,14.967123,A,8,2_13,1.04,2,32.0,30,0,0,0.000000,0.000000,0,0,3
2648,2649,308,0,9.315068,A,12,7_46,0.54,1,37.0,29,0,0,0.000000,0.000000,0,0,
577,578,441,0,4.953425,A,14,1_9,1.70,2,28.0,22,0,0,0.000000,0.000000,0,2843,1
578,579,441,0,12.013699,A,14,2_7,1.22,2,28.0,34,0,0,0.000000,0.000000,0,2843,2
589,590,442,0,2.835616,A,14,7_31,1.37,1,30.0,19,0,0,0.000000,0.000000,0,200,
587,588,450,0,6.446575,A,14,7_38,0.39,1,57.0,26,0,0,0.000000,0.000000,800,0,1
588,589,450,0,6.726027,A,14,1_23,1.01,2,57.0,27,0,0,0.000000,0.000000,800,0,2
581,582,453,1,14.046575,A,14,3_4,1.21,2,48.0,75,0,51,0.000000,5.378082,430,2541,1
582,583,453,1,16.936986,A,14,7_27,0.26,1,48.0,92,0,51,0.000000,5.378082,430,2541,2
583,584,455,0,4.969863,A,14,1_13,1.67,2,33.1,22,0,0,0.000000,0.000000,0,0,
585,586,458,0,4.958904,A,14,8_12,1.60,1,9.0,22,0,0,0.000000,0.000000,790,170,1
584,585,458,0,11.350685,A,14,2_6,1.04,2,9.0,31,0,0,0.000000,0.000000,790,170,2
580,581,459,0,7.282192,A,14,7_27,1.02,1,39.0,29,207,65,3.668493,4.939726,207,65,1
579,580,459,0,9.961644,A,14,4_3,1.01,2,39.0,41,207,65,3.668493,4.939726,207,65,2
575,576,467,1,5.605479,A,14,1_40,1.07,2,47.0,23,0,176,0.000000,3.860274,0,0,
591,592,476,0,7.304110,A,14,8_5,0.61,1,86.0,29,0,0,0.000000,0.000000,0,0,
590,591,477,1,4.953425,A,14,1_12,1.13,2,86.0,22,0,0,0.000000,0.000000,0,0,
2653,2654,494,1,4.915068,A,12,8_19,0.70,1,29.0,19,0,0,0.000000,0.000000,0,0,

### RTL and Terr

Need to find what Terr values mean on a map

plot RTL by Terr on heat map to see if there are any environmental factors effecting RTL